import React from 'react'
import { Link } from 'react-router-dom'

export default function Privacy() {
  return (
    <div className='page-container me-5 ms-5 mt-2'>
  
  
    <div className='privacy-container'>
    <h2 className='text-center'>Privacy Statement</h2>
        <p className='text-center' style={{color:'gray'}}>Effective Date: January 12, 2023</p>
        <p>MuniTask Company (“Company”, “we”, “us”, or “our”) values the trust you place in us when you use our affiliated websites, applications, and  online services (collectively, our “Websites”). This Privacy Statement describes our collection, use, disclosure and retention of information we collect from or about you. This Privacy Statement applies to our Websites that post or link to it, regardless of how you access or use them, including through mobile devices. </p>
        <p> BY USING OUR WEBSITES, YOU ARE ACCEPTING THE TERMS OF THIS PRIVACY STATEMENT AND OUR <Link to='/termsofservice'>TERMS OF SERVICE</Link>, AND YOU ARE CONSENTING TO OUR COLLECTION, USE, DISCLOSURE, AND RETENTION OF INFORMATION AS DESCRIBED IN THIS PRIVACY STATEMENT.</p>
        <p> If you do not agree to the terms of this Privacy Statement, please do not use our Websites. We may make changes to this Privacy Statement from time to time. We will post any changes to our Websites. Your continued use of our Websites following the posting of any changes will mean you accept those changes. </p>
        <p>This Privacy Statement does not apply to information that you may submit to us offline, or to third-party websites or mobile applications that may link to the Websites or be linked to on the Websites. We are not responsible for the actions or privacy practices of third-party websites and applications; please consult those websites and applications directly to understand their privacy practices. </p>
    <h3>INFORMATION WE COLLECT ABOUT YOU</h3>
        <p>We collect, process, and retain information from you and any devices you may use when you use or interact with our Websites, and in other ways described below. </p>
            <h5>Information You Give Us</h5>
                <p>We receive and store information provided to our Websites or given to use in any other way, including any and all information relating to creating a profile and submitting a job interest form, but not limited to, your name, mailing address, phone number, email address, and social media username. </p>
            <h5>Information We Automatically Collect</h5>
                <p>We receive and store certain types of information whenever you use our Websites. Our Websites may use “cookies”, tagging and other tracking technologies to help enable us to enhance or personalize your online experience. This information includes computer and connection information, such as statistics on your page views, traffic to and from our Websites, referral URL, ad data, your IP address, device identifiers, user history, and your web log information.</p>
            <h5>Location Information</h5>
                <p>When you agree to share your location when prompted by your browser while visiting our Website, we may receive information about your location and your device, including a unique identifier for your device. Location information allows us to provide location-based services, such as automatic filtering of job search results by your location. We will only collect precise geo-location information with your consent; however, some services or features may not function properly without this information. See the <a href='#your-choices'> Your Choices</a> section below for more information. </p>
            <h5>Information From Social Media</h5>
                <p>When you interact with us or our Websites on a social media platform, we may collect the personal information that you make available to us, including your account identification, username, and other information included in your posts. If you choose to log into your account with or through a social networking service, we and that service may share certain information about you and your activities.</p>
            <h5>Information From Other Sources</h5>
                <p>We may supplement the information we collect with information offline or from third parties. This Privacy Statement does not apply to this other information. </p>
    <h3>HOW WE USE INFORMATION WE COLLECT FROM OR ABOUT YOU</h3>
        <p>We use the information we collect from or about you to help use personalize and continually improve your experience on the Websites, including providing our products and services, responding to requests for information, analyzing and compiling trends and statistics, and communicating with you. For information about how to manage information about you and the choices you have, see the <a href='#your-choices'> Your Choices</a> section below.</p>
        <p>We also may use information about you to: provide, maintain, and improve the Websites and for internal or other business purposes; fulfill requests for information; communicate with you; detect, investigate, and prevent activities that may violate our policies or be fraudulent or illegal; optimize, perform analysis, or improve our Websites, products, services, and operations; provide services you request; provide customer support; send you offers or other communications about our products and services, such as special or promotional events, including services, products, or events for which we collaborate or co-offer with a third party; administer contests, sweepstakes, promotions, surveys; and post user-generated content provided by users.</p>
        <p>We may use the information from one portion of the Websites on other portions of the Websites, and we may combine information gathered from multiple portions of the Websites. We also may use or combine information that we collect offline or we collect or receive from third-party sources for many reasons, including to enhance, expand, and check the accuracy of our records. Additionally, information collected from a particular browser or device may be used with another computer or device that is linked to the browser or device on which such information was collected.</p>
        <p>We may retain information we collect from or about you for as long as reasonably required to satisfy the purposes for which we have collected the information, or as required by law, whichever is longer. This means we will retain information about you both while you are an active user of our Websites and after you cease to be an active user. </p>
    <h3>HOW WE SHARE YOUR INFORMATION WITH OTHERS</h3>
        <p>We share information we collect from or about you with third parties as described below. In addition, we may share information that does not personally identify you, such as aggregate information, de-identified information, device identifiers, or other unique identifiers with third parties. For information about how to manage information about you and the choices you have, see the <a href='#your-choices'>Your Choices</a> section below.</p>
            <h5>Job Interest Forms</h5>
                <p>If you submit a job interest form for a position through our Website, all of the information contained in your job interest form, including any attachments, will be shared with the one or more entities that are associated with that job posting. We are not responsible for the use or disclosure of your information once it is provided to these third parties. </p>
            <h5>Third-Party Service Providers</h5>
                <p> We engage third-party service providers to perform functions on our behalf, such as hosting, content management, technical integration, marketing, analytics, and customer service. These third parties may have access to information about you when needed to perform their functions. </p>
            <h5>Sale, Assignment or Change of Control</h5>
                <p> We may change our ownership or corporate organization while providing the Websites. We may transfer some or all information about you in connection with, or during negotiations of, any merger, acquisition, sale of assets, or any line of business, change in ownership control, or financing transaction. Under such circumstances, we will request the acquiring party to follow the practices described in this Privacy Statement with respect to previously collected information. Nevertheless, we cannot promise that an acquiring party or merged entity will have the same privacy practices or treat information about you in the same way as described in this Privacy Statement. </p>
            <h5>Law Enforcement, Legal Process, and Emergency Situations</h5>
                <p>We may also use or disclose information we collect from or about you if required to do so by law or on the good-faith belief that such action is necessary to (a) conform to applicable law or comply with legal process served on us or our Websites; (b) protect and defend our rights to property, the Websites, or our users; (c) respond to a third-party that alleges that you have infringed their intellectual property rights; or (d) act to protect the personal safety of us, users of the Websites, or the public. </p>
            <h5>Public Areas, Interactive Features and Activities</h5>
                <p>Please remember that any information you share in public areas or on social sharing features, becomes public and anyone may take and use that information. Please be careful about what you disclose and do not post any information that you expect to keep private. Please consult the applicable guidelines, if any, for use of these features. We cannot control who views information that you post in public areas of the Websites and are not responsible for how third parties, including other users, may use or disclose information that you post or otherwise share with other users or third parties. If you are under the age of 18 and a registered user, you may have content or information you have posted removed from public display by contacting hello@munitask.com</p>
    <h3>HOW TO ACCESS AND UPDATE YOUR INFORMATION </h3>
        <p>If you have an account with use, you can update information about you by logging into https://munitask.com and clicking the ‘Account’ link in the navigation menu. If you would like to access or update any documents attached when submitting a job interest form, please contact us at hello@munitask.com. You will not be permitted to examine information related to any other person or entity. You may be required to provide us with sufficient information to verify your identity prior to accessing any records containing information about you. We may not accommodate a request to change information about you if we believe doing so would violate law or legal requirement, or cause the information to be incorrect or misleading. </p>
    <h3>COOKIES AND OTHER TRACKING TECHNOLOGIES </h3>
        <p>Like many websites, we use tracking technologies such as cookies, web beacons, and similar technologies to record your preferences, track the use of our Websites, and measure exposure to our online advertisements. We may also use these technologies to monitor traffic, improve the Websites, and make it easier to use and more relevant. Most web browsers automatically accept cookies but, if you prefer, you can usually modify your browser setting to disable or reject cookies. In addition, you may also render some web beacons unusable by rejecting or removing their associated cookies. If you delete your cookies or if you set your browser to decline cookies, some features of the Websites may not work or may not work as designed.</p>
        <p>We use third-party analytics services on the Websites, including Google Analytics. These analytics service providers use cookies or other tracking technologies to help us analyze how users interact with and use our Websites, compile reports about activity on Websites, and provide us with other services. The technologies may collect information such as your IP address, time of visit, whether you are a return visitor, any referring website, and other information. We do not use these analytics service providers to gather information that personally identifies you. The information generated by Google Analytics will be transmitted to and stored by Google and will be subject to Google's <a href='https://policies.google.com/privacy'>privacy policies</a>. To learn more about Google's partner services and to learn how to opt out of tracking of analytics by Google click <a href='https://policies.google.com/technologies/partner-sites'>here</a>.</p>
        <p>We work with third-party companies who also use these technologies to provide advertisements on our Websites and other third-party websites. These third parties may use these technologies to collect information about you when you use the Websites. They may collect information about your online activities over time and across different websites and other online services. They may also use persistent identifiers to track your Internet usage across other websites in their networks beyond our Websites. They may use this information to provide you with interest-based advertising or other targeted content. While we do not knowingly provide these entities with information that personally identifies you, such third parties may, with sufficient data from other sources, be able to personally identify you, unknown to us.</p>
        <p>Some content, applications, and advertisements on the Websites may be served by unaffiliated third parties. We do not control these third parties' tracking technologies or how they may be used. We are not responsible for the content or privacy practices on any website not operated by us to which our Websites links or that links to our Websites.</p>
        <p>Your browser or device may include ‘Do Not Track’ functionality. Our information collection, disclosure practices, and the choices that we provide will continue to operate as described in this Privacy Statement, whether or not a ‘Do Not Track’ signal is received.</p>
    <h3 id='your-choices'> YOUR CHOICES ABOUT HOW INFORMATION ABOUT YOU IS USED AND SHARED</h3>
        <p>In many instances, you have choices about the information you provide and how we use that information. These choices are described below.</p>
        <h5>Marketing Emails</h5>
            <p>By providing us with an email address, you acknowledge that we may use your email address to communicate with you. While you cannot opt-out of receiving notifications and other service-related communications regarding your account or your transactions, you can opt-out of receiving promotional and other marketing emails from us.</p>
        <h5>Precise Location Information</h5>
            <p>Most mobile devices allow you to control or disable the use of precise location services by any application on your mobile device through the device's settings menu.</p>
        <h5>Interest-Based Advertising Choices</h5>
            <p>You also have choices related to interest-based advertising. Many browsers automatically accept cookies, but you can usually modify your browser's setting to decline cookies if you prefer. Note that if you choose to remove cookies, you may remove opt-out cookies that affect your advertising preferences.</p>
            <p>Many of the third-party advertisers that place tracking tools on our Websites are members of programs that offer you additional choices regarding the use of information about you for advertising. You can learn more about the options available to limit these third parties' use of your information by visiting the websites for the <a href='http://www.networkadvertising.org/choices/'>Network Advertising Initiative</a> and the <a href='http://www.aboutads.info/choices/'>Digital Advertising Alliance</a>, as well as the <a href='https://www.facebook.com/about/ads'>Facebook</a> and <a href='https://adssettings.google.com/'>Google AdWords</a>.</p>
            <p>Similarly, you can learn about your options to opt-out of mobile app tracking by certain advertising networks through your device settings. For more information about how to change these settings, see the support information for <a href='https://support.apple.com/en-us/HT205223'>Apple</a>, <a href='https://policies.google.com/technologies/ads'>Android</a> or <a href='http://choice.microsoft.com/en-US/opt-out'>Windows</a> devices.</p>
            <p>Please note that opting-out of participating advertising networks services does not mean that you will not receive advertising while using our Websites or on other websites, nor will it prevent the receipt of interest-based advertising from third parties that do not participate in these industry programs.</p>
    <h3> OTHER IMPORTANT INFORMATION</h3>
        <h5>Users Under Thirteen</h5>
            <p>Our Websites are intended for users ages 13 and older only. If we become aware of information in our database that was collected from a child under 13, we will delete such information. </p>
            <p>We do not knowingly gather personal information (as defined by the United States Children’s Privacy Protection Act, or “COPPA”) in a manner not permitted by COPPA. If you are a parent or legal guardian and you believe that we have collected information from your child in a manner not permitted by law, please let us know by contacting us at hello@munitask.com. We will remove any data not permitted by COPPA.</p>
        <h5>Users Outside of the United States</h5>
            <p>If you use our Websites outside of the United States, you understand and consent to the transfer of information we collect from or about you to, and the collection, processing, and storage of information about you in, the United States and elsewhere. The laws in the United States and these countries may be different from the laws in your country. </p>
        <p><b>For questions about our Privacy Statement, you can contact us at hello@munitask.com.</b> </p>
        <p>All rights reserved. </p>
   
     
    </div>
    </div>
  )
}
